Template.addperson.onRendered ->
  @$('#select').dropdown()
  @$("#datepicker").datepicker()
  #console.log "Carl"
  @$('#illnesshide').hide()
  return

Template.addperson.events

  'submit #new-person': (event) ->
    # Prevent default browser form submit
    event.preventDefault()
    # Get value from form element
    target = event.target
    hebrewname = target.hebrewname.value

    console.log name
    return

  'click #select': ->
    #console.log "carl"
    $('.ui.dropdown').dropdown()
    return
  'change #select': (event) ->
    val = event.target.value
    if val == "refuah"
      $('#illnesshide').show(effect="drop")
    return
  'click #datepicker': (event) ->
    $("#datepicker").datepicker()
    return

# ---
# generated by js2coffee 2.2.0
