Meteor.subscribe 'people'


Template.addperson.onRendered ->
  @$('#select').dropdown()
  @$("#datepicker").datepicker()
  #console.log "Carl"
  @$('#illnesshide').hide()
  return

Template.addperson.events

  'submit #new-person': (event) ->
    # Prevent default browser form submit
    event.preventDefault()
    target = event.target
    # Get value from form element
    person = {}
    person['hebrewname'] = target.hebrewname.value
    person['legalname'] = target.legalname.value
    person['todavenfor'] = target.dickshart.value
    if target.dickshart.value == "refuah"
      person['refuah'] = target.illnesstype.value
    person['age'] = target.age.value
    person['location'] = target.location.value
    person['extra'] = target.extra.value
    console.log person
    Meteor.call 'peopleinsert', person
    return

  'click #select': ->
    #console.log "carl"
    $('.ui.dropdown').dropdown()
    return
  'change #select': (event) ->
    val = event.target.value
    if val == "refuah"
      $('#illnesshide').show()
    else
      $('#illnesshide').hide()
    return

# ---
# generated by js2coffee 2.2.0
