FlowRouter.route '/',
  action: ->
    BlazeLayout.render 'layout', content: 'home'
    return
  name: 'Home'

FlowRouter.route '/addperson',
  action: ->
    BlazeLayout.render 'layout', content: 'addperson'
    return
  name: 'Add a Person'

FlowRouter.route '/login',
  action: ->
    BlazeLayout.render 'layout', content: 'login'
    return
  name: 'Login'

FlowRouter.route '/signup',
  action: ->
    BlazeLayout.render 'layout', content: 'signup'
    return
  name: 'Sign up'

AccountsTemplates.configureRoute 'signIn', path: '/login'
AccountsTemplates.configureRoute 'signUp', path: '/signup'


# ---
# generated by js2coffee 2.2.0
